### ISSUE TITLE
CI workflows fail if no detector files are changed

### ISSUE THREAD

**Issue by mariakzurek** [gemc/clas12-oldsystems#12]
I'm trying to add an exit code to the comparison script, and wanted to verify that it works as expected in the CI. However, pushing these changes causes all CI workflows to fail. As I understand, this is because the commit doesn't affect any detector files, which in turn means that the dynamically-generated job matrix is empty: see e.g. https://github.com/mariakzurek/clas12-systems/actions/runs/2355550531.

**Comment by maureeungaro** [comment]
Fixed in ci: workflow inactivated if changes are irrelevant.
